### ISSUE TITLE
[ColorPicker]手动在颜色输入框中输入非法的颜色值会导致报错

### ISSUE THREAD

**Issue by kagol** [devui-complementary/nb-devui#39]
比如输入：#17504，点击确定，然后再次弹出颜色选择组件时会报错，并且最近颜色列表里会记录该非法颜色。
<img width="1824" alt="图片" src="https://user-images.githubusercontent.com/9566362/74603781-0be3af00-50f2-11ea-8529-82c140d21197.png">

<img width="809" alt="图片" src="https://user-images.githubusercontent.com/9566362/74603799-2ddd3180-50f2-11ea-8076-2fd7415f342b.png">

**Comment by guxi11** [comment]
在pr#41中解决了
