### ISSUE TITLE
[ColorPicker]最近颜色中的清除颜色按钮不应该清空最近颜色列表，而是清除设置的颜色

### ISSUE THREAD

**Issue by kagol** [devui-complementary/nb-devui#40]
这个按钮的功能是将设置好的颜色清除掉，不是清空最近颜色列表。

<img width="650" alt="图片" src="https://user-images.githubusercontent.com/9566362/74603816-611fc080-50f2-11ea-88e9-f9ef815695d7.png">

**Comment by guxi11** [comment]
在pr#41中解决了
